bundle_root: .
decathlon_data_list: .
data_dir: .
fill_value:
- 0
- 0.2
patch_size:
- 96
- 96
- 96
batch_size: 2
max_epochs: 500
val_interval: 5
lr: 0.0001
in_channels: 2
out_channels: 2
embed_dim: 96

ckpt_dir: "$@bundle_root + '/models'"
log_dir: "$@bundle_root + '/logs'"
mlflow_experiment_name: SSL
num_train_batches_per_epoch: 574
mlflow_run_name: AutoPET_SwinAutoEnc
tracking_uri: "http://localhost:5000"